# Generated by Django 3.1.7 on 2021-04-13 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210413_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserD',
            new_name='Profile',
        ),
    ]
