# Generated by Django 3.1.7 on 2021-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.CharField(max_length=50),
        ),
    ]
